"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _task_card from './task-card.bones.json'

registerBones({
  "task-card": _task_card,
})
